apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: jpetstore-prd
  labels:
    run: tomcat
spec:
  type: NodePort
  ports:
  - port: 8080  
    protocol: TCP
    nodePort: 30500
  selector:
    app: tomcat